### ISSUE TITLE
Mixins with "+" notation cannot be used with nested content

### ISSUE THREAD

**Issue by themeler** [TheRealSyler/sass-formatter#16] opened 2020-03-09 13:49 UTC
Using `+mixin-name` for media queries is now impossible, as formatter lines up mixin content.

**To Reproduce**

Before using formatter (original code):
```
=on-large-screen
    @media screen and (min-width: $1441px)
        @content

...

.class
    padding: 30px
    +on-large-screen
        padding: 60px
```

After using formatter:
```
=on-large-screen
    @media screen and (min-width: $1441px)
        @content

...

.class
    padding: 30px
    +on-large-screen
    padding: 60px
```

**Expected behavior**
```
=on-large-screen
    @media screen and (min-width: $app-max-width + 1px)
        @content

...

.class
    padding: 30px
    +on-large-screen
        padding: 60px
```

**Desktop:**
 - OS: Windows 10
 - Version (of the extension): Vetur 0.24.0 (I assume the latest, didn't find it anywhere)

Note:
Using `@include` does not break formatting.

**Comment by TheRealSyler** [comment] 2020-03-09 13:59
@themeler since there is no way of knowing if a user wants to add `@content` to the mixin i decided that `@include` always indents the following properties and `+mixin` can be used to add mixins without indenting the following properties.

maybe its a good idea to add a note to the readme or something, but this is not a bug and therefore i will close the issue as expected behavior.

**Closed by TheRealSyler** 2020-03-09 13:59 UTC
Labels: bug
